-- Generated by Mocodo 4.2.4

CREATE TABLE Commentaire (
  PRIMARY KEY (id),
  id        VARCHAR(42) NOT NULL,
  date      VARCHAR(42),
  contenu   VARCHAR(42),
  id_post   VARCHAR(42) NOT NULL,
  id_parent VARCHAR(42) NULL
);

CREATE TABLE Post (
  PRIMARY KEY (id),
  id      VARCHAR(42) NOT NULL,
  date    VARCHAR(42),
  contenu VARCHAR(42)
);

ALTER TABLE Commentaire ADD FOREIGN KEY (id_parent) REFERENCES Commentaire (id);
ALTER TABLE Commentaire ADD FOREIGN KEY (id_post) REFERENCES Post (id);
